export const hospitaldeatils=[
  {
    "name": "Academic Hospital Bogenhausen",
    "hospitalImages": [
      "https://d1ea147o02h74h.cloudfront.net/hospitals/academic_hospital_bogenhausen_munich-min.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/ot-min_20.jpg"
    ],
    "about": "Academic Hospital Bogenhausen is an academic teaching hospital for the University of Munich. It specializes in lung diseases, especially heart diseases, hormonal disorders, respiratory diseases, lung diseases, lung cancer and more. The facility receives more than 36,000 clinical cases in a year.",
    "location": "Munich, Germany",
    "rating": 4.7,
    "numberOfBeds": 1000,
    "specialty": "Multi Specialty",
    "establishedIn": 0,
    "accreditations": [],
    "departments": [
      "Cardiology and Cardiac Surgery",
      "Cosmetic and Plastic Surgery",
      "Neurology and Neurosurgery",
      "Oncology and Oncosurgery",
      "Orthopedics"
    ],
    "facilities": [
      "TV in room",
      "Private rooms",
      "Free Wifi",
      "Phone in Room",
      "Mobility accessible rooms",
      "Family accommodation",
      "Laundry",
      "Welcome",
      "Safe in the room",
      "Nursery / Nanny services",
      "Dry cleaning",
      "Personal assistance / Concierge",
      "Religious facilities",
      "Fitness",
      "Spa and wellness",
      "Café",
      "Business centre services",
      "Shop",
      "Dedicated smoking areas",
      "Beauty Salon",
      "Special offer for group stays",
      "Parking available",
      "Health insurance coordination",
      "Medical travel insurance",
      "Foreign currency exchange",
      "ATM",
      "Credit Card",
      "Debit Card",
      "Netbanking",
      "Diet on Request",
      "Restaurant",
      "International Cuisine",
      "Self-Cooking",
      "Medical records transfer",
      "Online doctor consultation",
      "Rehabilitation",
      "Pharmacy",
      "Document legalisation",
      "Post operative followup",
      "Interpreter",
      "Translation services",
      "Airport pickup",
      "Local tourism options",
      "Local transportation booking",
      "Visa / Travel office",
      "Car Hire",
      "Private driver / Limousine services",
      "Shopping trip organisation",
      "Air ambulance"
    ],
    "address": {
      "street": "Englschalkinger Straße 77",
      "city": "Munich",
      "state": "",
      "zipCode": "81925",
      "country": "Germany"
    }
  },
  {
    "name": "Asklepios Hospital Barmbek",
    "hospitalImages": [
      "https://d1ea147o02h74h.cloudfront.net/hospitals/asklepios_hospital_barmbek_hamburg-min.jpeg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/inner-hospital-min.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/reception-min_29.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/waiting-area-min_23.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/mri_scan-min_0.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/room1-min_1.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/room-min_4.jpg"
    ],
    "about": "Founded in 2005, Asklepios Hospital Barmbek is a part of the Asklepios medical group, a major network of private clinics in Germany. The hospital is known for its state-of-the-art medical standards and specializes in various medical fields, particularly treatment for liver diseases and advanced quality medical tourism services.",
    "location": "Hamburg, Germany",
    "rating": 3.6,
    "numberOfBeds": 620,
    "specialty": "Super Specialty",
    "establishedIn": 2015,
    "accreditations": ["NABH", "EFQM"],
    "departments": [
      "Cardiology",
      "Cosmetic and Plastic Surgery",
      "ENT Surgery",
      "Gastroenterology",
      "Gynecology",
      "Hematology",
      "Neurology and Neurosurgery",
      "Oncology and Oncosurgery",
      "Orthopedics",
      "Pediatric Cardiology",
      "Pediatrics and Pediatric Surgery",
      "Urology",
      "Vascular Surgery"
    ],
    "facilities": [
      "Free Wifi",
      "Private rooms",
      "Laundry",
      "Family accommodation",
      "Health insurance coordination",
      "Medical travel insurance",
      "Restaurant",
      "Spa and wellness",
      "Airport pickup"
    ],
    "address": {
      "street": "Rubenkamp 220",
      "city": "Hamburg",
      "state": "Hamburg",
      "zipCode": "22307",
      "country": "Germany"
    }
  },
  {
    "name": "Asklepios Academic City Hospital, Bad Wildungen",
    "hospitalImages": [
      "https://d1ea147o02h74h.cloudfront.net/hospitals/asklepios_academic_city_hospital_bad_wildungen-min.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/ot-min_16.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/hospital-min_2.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/room-min_5.jpg"
    ],
    "about": "Asklepios Academic City Hospital is an academic teaching hospital located in Northern Hesse, Germany. It is affiliated with the Phillip University of Magburg and is a member of Asklepios Clinics GmbH. Known for its advanced medical procedures and state-of-the-art equipment, the hospital has a strong reputation both in Germany and internationally. It features high-tech operating rooms, is set in a lush green area, and is designed to accommodate 210 inpatients while offering high-quality medical care.",
    "location": "Bad Wildungen, Germany",
    "rating": 4.4,
    "numberOfBeds": 210,
    "specialty": "Multi Specialty",
    "establishedIn": 0,
    "accreditations": [],
    "departments": [
      "CARDIOLOGY AND CARDIAC SURGERY",
      "COSMETIC AND PLASTIC SURGERY",
      "GYNECOLOGY",
      "NEUROLOGY AND NEUROSURGERY",
      "ORTHOPEDICS",
      "UROLOGY TREATMENT",
      "VASCULAR SURGERY"
    ],
    "facilities": [
      "TV in room",
      "Private rooms",
      "Free Wifi",
      "Phone in Room",
      "Mobility accessible rooms",
      "Family accommodation",
      "Laundry",
      "Safe in the room",
      "Fitness",
      "Spa and wellness",
      "Café",
      "Business centre services",
      "Shop",
      "Beauty Salon",
      "Parking available",
      "Diet on Request",
      "Online doctor consultation"
    ],
    "address": {
      "street": "Brunnenallee 19",
      "city": "Bad Wildungen",
      "state": "",
      "zipCode": "34537",
      "country": "Germany"
    }
  },
  {
    "name": "Alfried Krupp Hospital, Essen",
    "hospitalImages": [
      "https://d1ea147o02h74h.cloudfront.net/hospitals/1-min_13.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/2-min_12.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/3-min_12.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/4-min_11.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/5-min_11.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/6-min_12.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/7-min_9.jpg",
      "https://d1ea147o02h74h.cloudfront.net/hospitals/8-min_9.jpg"
    ],
    "about": "The Alfried Krupp Hospital is an extensive medical center based in Essen, Germany, founded in the year 1872. With a capacity of 573 beds, approximately 28,067 medical cases are treated in specialized departments every year. The hospital features state-of-the-art medical technology and an experienced staff, ensuring high-quality services and care.",
    "location": "Essen, Germany",
    "rating": 4.7,
    "numberOfBeds": 573,
    "specialty": "Multi Specialty",
    "establishedIn": 1872,
    "accreditations": [],
    "departments": [
      "Anesthesia",
      "General & Visceral Surgery",
      "Vascular Medicine",
      "Gynecology",
      "Ear, Nose and Throat (ENT)",
      "Hematology & Oncology",
      "Cardiology",
      "Nephrology",
      "Neurosurgery",
      "Neurology",
      "Orthopedics",
      "Pulmonology",
      "Plastic Surgery",
      "Radiology & Neuroradiology",
      "Radiation Oncology",
      "Trauma Surgery",
      "Urology"
    ],
    "facilities": [
      "TV in room",
      "Private rooms",
      "Free Wifi",
      "Phone in Room",
      "Mobility accessible rooms",
      "Family accommodation",
      "Laundry",
      "Welcome",
      "Safe in the room",
      "Nursery / Nanny services",
      "Dry cleaning",
      "Personal assistance / Concierge",
      "Religious facilities",
      "Fitness",
      "Spa and wellness",
      "Café",
      "Business centre services",
      "Shop",
      "Dedicated smoking areas",
      "Beauty Salon",
      "Special offer for group stays",
      "Parking available"
    ],
    "address": {
      "street": "Alfried-Krupp-Strasse 21",
      "city": "Essen",
      "state": "",
      "zipCode": "45131",
      "country": "Germany"
    }
  }
]